import { colors } from './colors';
import { shadows } from './shadows';
import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

export const createTestsStyles = (isTablet: boolean) => {
  const imageSize = isTablet ? wp('5%') : wp('12%');
  const modelImageSize = isTablet ? wp('8%') : wp('15%');
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: isTablet ? wp('4%') : wp('5%'),
      paddingTop: isTablet ? hp('4%') : hp('7%'),
      paddingBottom: isTablet ? hp('0.5%') : hp('3%'),
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderBottomColor: colors.outlineBorder,
    },
    backButton: {
      width: isTablet ? hp('6%') : hp('5%'),
      height: isTablet ? hp('6%') : hp('5%'),
      borderRadius: isTablet ? hp('3%') : hp('2.5%'),
      backgroundColor: colors.secondary,
      alignItems: 'center',
      justifyContent: 'center',
      ...shadows.shadowDefault,
    },
    backButtonText: {
      fontSize: isTablet ? wp('7%') : wp('5%'),
      fontWeight: '600',
      color: colors.foreground,
      marginTop: isTablet ? wp('-1.5%') : wp('5%'),
    },
    headerSpacer: {
      width: isTablet ? hp('3%') : hp('5%'),
    },
    searchSection: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: isTablet ? wp('4%') : wp('5%'),
      paddingVertical: isTablet ? hp('2%') : hp('2.5%'),
      gap: isTablet ? wp('3%') : wp('3%'),
    },
    searchContainer: {
      flex: 1,
      backgroundColor: colors.card,
      borderRadius: isTablet ? 16 : 12,
      borderWidth: 1,
      borderColor: colors.outlineBorder,
      ...shadows.shadowDefault,
    },
    searchInput: {
      paddingHorizontal: isTablet ? wp('4%') : wp('4%'),
      paddingVertical: isTablet ? hp('1.8%') : hp('2%'),
      fontSize: isTablet ? wp('3.5%') : wp('4%'),
      color: colors.foreground,
    },
    filterButton: {
      width: isTablet ? hp('6%') : hp('5.5%'),
      height: isTablet ? hp('6%') : hp('5.5%'),
      borderRadius: isTablet ? 16 : 12,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      ...shadows.shadowDefault,
    },
    filterButtonText: {
      fontSize: isTablet ? wp('4%') : wp('4.5%'),
      color: colors.primaryForeground,
    },
    listContainer: {
      flex: 1,
      paddingHorizontal: isTablet ? wp('4%') : wp('5%'),
      paddingTop: isTablet ? wp('3%') : wp('0%')
    },
    testsList: {
      gap: isTablet ? hp('1.5%') : hp('2%'),
      paddingBottom: isTablet ? hp('3%') : hp('4%'),
    },
    testCard: {
      marginVertical: 0,
      padding: isTablet ? wp('4%') : wp('4%'),
      borderRadius: isTablet ? 20 : 16,
      ...shadows.shadowMedium,
    },
    testCardContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    testInfo: {
      flex: 1,
      gap: isTablet ? hp('1%') : hp('1.2%'),
    },
    testHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: isTablet ? hp('0.5%') : hp('0.8%'),
    },
    testName: {
      fontSize: isTablet ? wp('4%') : wp('4.5%'),
      fontWeight: '600',
      color: colors.foreground,
      flex: 1,
    },
    testDescription: {
      fontSize: isTablet ? wp('3%') : wp('3.5%'),
      color: colors.mutedForeground,
    },
    emptyState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: isTablet ? wp('10%') : wp('8%'),
      gap: isTablet ? hp('2%') : hp('2.5%'),
    },
    emptyStateTitle: {
      fontSize: isTablet ? wp('4.5%') : wp('5%'),
      fontWeight: '600',
      color: colors.foreground,
      textAlign: 'center',
    },
    emptyStateDescription: {
      fontSize: isTablet ? wp('3%') : wp('4%'),
      color: colors.mutedForeground,
      textAlign: 'center',
      lineHeight: isTablet ? hp('2%') : hp('3%'),
    },
    formContainer: {
      marginTop: isTablet ? hp('2%') : hp('3%'),
      backgroundColor: colors.card,
      borderRadius: isTablet ? wp('3%') : wp('2%'),
      padding: isTablet ? wp('5%') : wp('4%'),
      marginHorizontal: isTablet ? wp('4%') : wp('5%'),
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: hp('0.2%') },
      shadowOpacity: 0.1,
      shadowRadius: wp('1%'),
      elevation: 3,
      marginBottom: isTablet ? hp('2.5%') : hp('2%'),
    },
    labelTestName: {
      color: colors.mutedForeground,
      paddingVertical: isTablet ? hp('1%') : hp('1.5%'),
      fontSize: isTablet ? 20 : 14,
      fontWeight: '600',
    },
    label: {
      fontSize: isTablet ? wp('3.5%') : wp('4%'),
      color: colors.foreground,
      marginBottom: isTablet ? hp('1.5%') : hp('1%'),
      fontWeight: '500',
    },
    input: {
      height: isTablet ? hp('7%') : hp('6%'),
      borderColor: colors.outlineBorder,
      borderWidth: 1,
      borderRadius: isTablet ? 12 : 10,
      paddingHorizontal: wp('3.5%'),
      marginBottom: isTablet ? hp('2.5%') : hp('2%'),
      color: colors.foreground,
      backgroundColor: colors.card,
      fontSize: isTablet ? wp('3.5%') : wp('4%'),
      justifyContent: 'center'
    },
    picker: {
      height: isTablet ? hp('7%') : hp('6%'),
      width: '100%',
      backgroundColor: colors.card,
      borderRadius: isTablet ? 12 : 10,
      borderWidth: 1,
      borderColor: colors.outlineBorder,
      justifyContent: 'center',
      paddingHorizontal: wp('1%'),
      marginBottom: isTablet ? hp('2.5%') : hp('2%'),
      alignItems: 'center',
      paddingVertical: isTablet ? hp('2%') : hp('2.5%'),
    },
    startButton: {
      marginTop: isTablet ? hp('2%') : hp('3%'),
    },
    preparationContainer: {
      flex: 1,
      backgroundColor: colors.primaryForeground,
    },
    content: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: isTablet ? wp('10%') : wp('5%'),
    },
    title: {
      fontSize: isTablet ? wp('4.5%') : wp('8%'),
      fontWeight: 'bold',
      color: colors.purpleLight,
      marginBottom: hp('1%'),
      textAlign: 'center',
    },
    subtitle: {
      fontSize: isTablet ? wp('3%') : wp('5%'),
      color: colors.purpleLight,
      marginBottom: hp('1%'),
      textAlign: 'center',
    },
    testNamePreparation: {
      fontSize: isTablet ? wp('3.5%') : wp('6%'),
      fontWeight: '600',
      color: colors.purpleLight,
      marginBottom: hp('3%'),
      textAlign: 'center',
    },
    imageContainer: {
      width: isTablet ? wp('30%') : wp('60%'),
      height: isTablet ? hp('30%') : hp('40%'),
      justifyContent: 'center',
      alignItems: 'center',
      marginVertical: hp('2%'),
    },
    cogniImage: {
      width: '100%',
      height: '100%',
    },
    instructions: {
      fontSize: isTablet ? wp('4%') : wp('7%'),
      color: colors.purpleLight,
      textAlign: 'center',
      marginVertical: hp('2%'),
      lineHeight: isTablet ? hp('3%') : hp('4%'),
    },
    startButtonPreparation: {
      marginTop: hp('2%'),
      minWidth: isTablet ? wp('20%') : wp('50%'),
      backgroundColor: colors.purpleButton,
    },
    instructionsContainer: {
      flex: 1,
    },
    instructionsContent: {
      paddingHorizontal: isTablet ? wp('5%') : wp('6%'),
      paddingTop: isTablet ? hp('3%') : hp('5%'),
      paddingBottom: hp('3%'),
    },
    storyTitle: {
      fontSize: isTablet ? wp('4%') : wp('7%'),
      fontWeight: 'bold',
      color: colors.purpleLight,
      marginBottom: hp('1%'),
      textAlign: 'center',
    },
    sectionTitle: {
      fontSize: isTablet ? wp('3.5%') : wp('6%'),
      fontWeight: 'bold',
      color: colors.purpleLight,
      marginTop: hp('2.5%'),
      marginBottom: hp('1%'),
    },
    storyText: {
      fontSize: isTablet ? wp('3%') : wp('5.5%'),
      color: colors.purpleLight,
      lineHeight: isTablet ? hp('2%') : hp('2.5%'),
      marginBottom: hp('1.5%'),
      textAlign: 'justify',
    },
    highlight: {
      fontWeight: 'bold',
      color: colors.purpleLight,
    },
    stepContainer: {
      flexDirection: 'row',
      marginBottom: hp('1.2%'),
      alignItems: 'flex-start',
    },
    stepNumber: {
      fontSize: isTablet ? wp('2.5%') : wp('4.5%'),
      fontWeight: 'bold',
      color: colors.purpleLight,
      marginRight: wp('2.5%'),
    },
    stepText: {
      fontSize: isTablet ? wp('2.5%') : wp('4.5%'),
      color: colors.purpleLight,
      lineHeight: isTablet ? hp('2%') : hp('3%'),
      flex: 1,
    },
    finalMessage: {
      fontSize: isTablet ? wp('2.5%') : wp('4.5%'),
      color: colors.purpleLight,
      lineHeight: isTablet ? hp('2%') : hp('2.5%'),
      fontStyle: 'italic',
      textAlign: 'center',
      paddingHorizontal: wp('2.5%'),
    },
    letsGoButton: {
      minWidth: isTablet ? wp('20%') : wp('50%'),
      backgroundColor: colors.purpleButton,
      marginTop: hp('1%'),
    },
    buttonAndImageContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: isTablet ? wp('3%') : wp('5%'),
    },
    imageBesideButton: {
      width: isTablet ? wp('10%') : wp('30%'),
      height: isTablet ? hp('10%') : hp('15%'),
    },
    imageSmall: {
      width: '100%',
      height: '100%',
    },
    applicationContainer: {
      flex: 1,
      backgroundColor: colors.primaryForeground,
      marginTop: isTablet ? hp('2%') : hp('1%'),
    },
    headerContainer: {
      backgroundColor: colors.muted,
      paddingTop: isTablet ? hp('2%') : hp('3%'),
      paddingBottom: isTablet ? hp('1.5%') : hp('2%'),
      paddingHorizontal: isTablet ? wp('3%') : wp('4%'),
      borderBottomWidth: isTablet ? 3 : 2,
      borderBottomColor: colors.purpleLight,
      ...shadows.shadowMedium,
    },
    titleText: {
      fontSize: isTablet ? wp('3.5%') : wp('6%'),
      fontWeight: 'bold',
      marginBottom: isTablet ? hp('1.2%') : hp('1.5%'),
      textAlign: 'center',
      color: colors.purpleButton,
    },
    timerContainer: {
      backgroundColor: colors.purpleButton,
      padding: isTablet ? hp('1%') : hp('1.2%'),
      borderRadius: isTablet ? 12 : 10,
      marginBottom: isTablet ? hp('1.2%') : hp('1.5%'),
      alignItems: 'center',
      borderWidth: isTablet ? 2 : 1,
      borderColor: colors.purpleLight,
    },
    timerText: {
      fontSize: isTablet ? wp('2.5%') : wp('4.5%'),
      fontWeight: 'bold',
      color: colors.primaryForeground,
    },
    modelContainer: {
      alignItems: 'center',
      backgroundColor: colors.card,
      padding: isTablet ? wp('2%') : wp('4%'),
      borderRadius: isTablet ? 15 : 12,
      borderWidth: isTablet ? 4 : 2,
      borderColor: colors.purpleAccent,
      ...shadows.shadowMedium,
    },
    modelLabel: {
      fontSize: isTablet ? wp('2.5%') : wp('4.5%'),
      fontWeight: 'bold',
      marginBottom: isTablet ? hp('1%') : hp('1.2%'),
      color: colors.purpleButton,
      textAlign: 'center',
    },
    modelImageWrapper: {
      borderWidth: isTablet ? 4 : 2,
      borderColor: colors.softGreen,
      borderRadius: isTablet ? 15 : 10,
      padding: isTablet ? wp('1.5%') : wp('2%'),
      backgroundColor: colors.muted,
      position: 'relative',
    },
    modelImage: {
      width: modelImageSize,
      height: modelImageSize,
      borderRadius: isTablet ? 10 : 8,
      resizeMode: 'contain',
    },
    arrowIndicator: {
      position: 'absolute',
      bottom: isTablet ? hp('-3%') : hp('-4%'),
      alignSelf: 'center',
    },
    arrowText: {
      fontSize: isTablet ? wp('4%') : wp('8%'),
    },
    scrollContent: {
      paddingVertical: isTablet ? hp('2%') : hp('2.5%'),
      paddingHorizontal: isTablet ? wp('2%') : wp('3%'),
      backgroundColor: colors.background,
    },
    instructionText: {
      fontSize: isTablet ? wp('2.5%') : wp('4.5%'),
      textAlign: 'center',
      marginBottom: isTablet ? hp('2%') : hp('2.5%'),
      color: colors.purpleButton,
      paddingHorizontal: isTablet ? wp('2%') : wp('3%'),
      fontWeight: 'bold',
      backgroundColor: colors.muted,
      padding: isTablet ? hp('1.5%') : hp('2%'),
      borderRadius: isTablet ? 12 : 10,
      borderWidth: isTablet ? 2 : 1,
      borderColor: colors.purpleLight,
    },
    gridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      gap: isTablet ? wp('0.8%') : wp('1.5%'),
    },
    imageWrapper: {
      position: 'relative',
      margin: isTablet ? wp('0.4%') : wp('0.8%'),
      borderRadius: isTablet ? 8 : 6,
      borderWidth: isTablet ? 2 : 1,
      borderColor: colors.outlineBorder,
      backgroundColor: colors.card,
      padding: isTablet ? wp('0.3%') : wp('0.5%'),
    },
    imageWrapperMarked: {
      borderColor: colors.softGreen,
      borderWidth: isTablet ? 3 : 2,
      backgroundColor: colors.subtleBackground,
      transform: [{ scale: 0.95 }],
    },
    image: {
      width: imageSize,
      height: imageSize,
      borderRadius: isTablet ? 6 : 4,
      resizeMode: 'cover',
    },
    markContainer: {
      position: 'absolute',
      top: isTablet ? hp('-0.5%') : hp('-1%'),
      right: isTablet ? wp('-0.5%') : wp('-1%'),
      backgroundColor: colors.softGreen,
      borderRadius: isTablet ? 12 : 10,
      width: isTablet ? wp('3%') : wp('6%'),
      height: isTablet ? hp('3%') : hp('3.5%'),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: isTablet ? 2 : 1,
      borderColor: colors.primaryForeground,
    },
    markText: {
      color: colors.primaryForeground,
      fontSize: isTablet ? wp('2%') : wp('4%'),
      fontWeight: 'bold',
    },
    buttonsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: isTablet ? hp('3%') : hp('4%'),
      marginBottom: isTablet ? hp('4%') : hp('5%'),
      paddingHorizontal: isTablet ? wp('4%') : wp('5%'),
      gap: isTablet ? wp('3%') : wp('4%'),
    },
    cancelButton: {
      flex: 1,
      backgroundColor: colors.destructive,
    },
    finishButton: {
      flex: 1,
      backgroundColor: colors.purpleButton,
    },
    pickerContainer: {
      backgroundColor: colors.card,
      borderRadius: isTablet ? 16 : 12,
      borderWidth: 1,
      borderColor: colors.outlineBorder,
      height: isTablet ? hp('5.5%') : hp('6%'),
      justifyContent: 'center',
      overflow: 'hidden',
      ...shadows.shadowDefault,
    },
    pickerFill: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      color: colors.foreground,
    },
  });
};